name: 'Notify AWS SNS Topic'
description: Sends an AWS SNS notification
inputs:
  message:
    description: 'Message to send to SNS Topic'
    required: true
    default: 'Hello World'
  topic_arn:
    description: 'Topic ARN to deliver to'
    required: true
outputs:
  sns_id:
    description: 'SNS Message ID'
runs:
  using: 'node20'
  main: 'index.js'
